# Generated by Django 4.2.29 on 2026-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_startingbalance_amount_pence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(
                max_length=10,
                choices=[('income', 'Income'), ('expense', 'Expense')],
                default='expense',  # or 'income', as appropriate
            ),
            preserve_default=False,
        ),
    ]
