# Generated by Django 4.2.29 on 2026-03-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_rename_kind_to_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_dd',
            field=models.BooleanField(default=False, help_text='Direct Debit (for expenses)'),
        ),
    ]
